#!/usr/bin/env python3

import pandas as pd
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
import jinja2
import numpy as np
from pathlib import Path
import sys
import argparse
import datetime
import json


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Interactive HTML Report Generator for OTU Pipeline."
    )
    parser.add_argument(
        "-f", "--filter_report",
        help="Path to filter report (TSV or XLSX)",
        required=True, type=str
    )
    parser.add_argument(
        "-otu", "--otu_table",
        help="Path to Excel file 'Final_OTU_Table.xlsx'",
        required=True, type=str
    )
    parser.add_argument(
        "-o", "--output_html",
        help="Path for output HTML file (e.g., 'MyReport.html').",
        required=True, type=str
    )
    parser.add_argument(
        "-pn", "--project_name",
        help="[Optional] Project name to display on report.",
        type=str, default="Metagenomic Analysis Report"
    )
    parser.add_argument(
        "-otuem", "--otu_table_em",
        help="[Optional] Path to the EM OTU table (OTU_Table_..._EM.xlsx). "
             "When given, the report shows how much abundance the EM moved "
             "relative to primary counts.",
        type=str, default=None
    )
    parser.add_argument(
        "-ms", "--mapping_stats",
        help="[Optional] Path to mapping_stats.json generated by the pipeline.",
        type=str, default=None
    )
    parser.add_argument(
        "--min-len", dest="min_len",
        help="Min sequence length used for filtering (0 = disabled).",
        type=int, default=None
    )
    parser.add_argument(
        "--max-len", dest="max_len",
        help="Max sequence length used for filtering (0 or 999999 = disabled).",
        type=int, default=None
    )
    return parser.parse_args()


def extract_filter_params(filter_report_path, cli_min_len, cli_max_len, mapping_data):
    """Build a dict of analysis parameters for the report header.

    Length filter values come from CLI args or, as fallback, from the
    filter-report filename (e.g. report_filtering_1000_3000.tsv).
    Quality filter values come from mapping_stats.json when available.
    """
    import re

    params = {}

    # --- Length filter ---
    min_len = cli_min_len
    max_len = cli_max_len

    # Fallback: parse from filename  report_filtering_<min>_<max>.tsv
    if min_len is None or max_len is None:
        m = re.search(r'report_filtering_(\d+)_(\d+)', str(filter_report_path))
        if m:
            if min_len is None:
                min_len = int(m.group(1))
            if max_len is None:
                max_len = int(m.group(2))

    if min_len is not None and max_len is not None:
        # Treat 0/999999 as "disabled"
        len_active = not (min_len == 0 and max_len >= 999999)
        params['len_filter_active'] = len_active
        params['min_len'] = min_len
        params['max_len'] = max_len
    else:
        params['len_filter_active'] = None   # unknown
        params['min_len'] = None
        params['max_len'] = None

    # --- Quality filter (from mapping_stats.json) ---
    if mapping_data:
        mp = mapping_data.get('parameters', {})
        min_id = mp.get('min_percent_identity', 0.0)
        min_cov = mp.get('min_ref_coverage', 0.0)
    else:
        min_id = 0.0
        min_cov = 0.0

    params['quality_filter_active'] = min_id > 0 or min_cov > 0
    params['min_percent_identity'] = min_id
    params['min_ref_coverage'] = min_cov

    return params


def load_mapping_stats(mapping_stats_path):
    """Load mapping_stats.json if present, return (stats_dict, error_msg)."""
    if not mapping_stats_path:
        return None, None
    try:
        with open(mapping_stats_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(f"Mapping stats loaded from: {mapping_stats_path}")
        return data, None
    except Exception as e:
        msg = f"WARNING: Cannot read mapping stats file: {e}"
        print(msg, file=sys.stderr)
        return None, msg


def get_mapping_kpis(mapping_data):
    """Compute mapping KPI cards from mapping_stats dict."""
    summary = mapping_data.get('summary', {})
    params = mapping_data.get('parameters', {})
    total = summary.get('total_reads_all', 0)
    mapped = summary.get('total_mapped_all', 0)
    filtered = summary.get('total_after_quality_filter', 0)
    mapping_rate = summary.get('overall_mapping_rate_pct', 0.0)
    retention = summary.get('overall_quality_retention_pct', 100.0)
    min_id = params.get('min_percent_identity', 0.0)
    min_cov = params.get('min_ref_coverage', 0.0)
    quality_filter_active = min_id > 0 or min_cov > 0
    return {
        'total_reads': f"{total:,}",
        'mapped_reads': f"{mapped:,}",
        'mapping_rate': f"{mapping_rate:.1f}%",
        'reads_after_quality_filter': f"{filtered:,}",
        'quality_retention': f"{retention:.1f}%",
        'quality_filter_active': quality_filter_active,
        'min_percent_identity': min_id,
        'min_ref_coverage': min_cov,
    }


def get_taxquality_kpis(mapping_data):
    """Aggregate the taxonomic-quality / noise blocks (Features A & C) into
    report KPI values.  Returns None when no sample carries these blocks.

    Every value reports what was actually MEASURED.  Cards for measurements
    that did not run are suppressed rather than defaulted to zero — a
    fabricated "0.0% chimeras" is indistinguishable from a genuinely clean run
    and is the most dangerous thing this report could print.
    """
    samples = mapping_data.get('samples', [])
    params = mapping_data.get('parameters', {})

    has_resolution = any('taxonomic_quality' in s for s in samples)
    has_noise = any('noise' in s for s in samples)
    has_supp = any('supplementary_count' in s for s in samples)
    if not (has_resolution or has_noise or has_supp):
        return None

    # --- Resolution (read-weighted across samples) ---
    tot_reads = 0
    species_reads = 0.0
    support_weighted = 0.0
    for s in samples:
        tq = s.get('taxonomic_quality')
        if not tq:
            continue
        n = tq.get('n_reads', 0)
        tot_reads += n
        species_reads += tq.get('pct_reads_species', 0.0) / 100.0 * n
        support_weighted += tq.get('mean_support', 0.0) * n
    pct_species = round(species_reads / tot_reads * 100, 1) if tot_reads else 0.0
    mean_support = round(support_weighted / tot_reads, 3) if tot_reads else 0.0

    # --- Noise / chimera ---
    # Tier 2 (per-read, from the read-level pass) and Tier 1 (flagstat
    # segments) are DIFFERENT quantities and are reported under different
    # labels; they are never silently substituted for one another.
    split_pct = None
    split_label = None
    chimera_refined = None
    if has_noise:
        tot_mapped = sum(s['noise'].get('n_mapped_reads', 0)
                         for s in samples if 'noise' in s)
        split_reads = sum(s['noise'].get('split_reads', 0)
                          for s in samples if 'noise' in s)
        split_pct = round(split_reads / tot_mapped * 100, 2) if tot_mapped else 0.0
        split_label = 'Split / Chimeric Reads'
        if any(s['noise'].get('refined_available') for s in samples if 'noise' in s):
            chim = sum(s['noise'].get('n_candidate_chimeras', 0)
                       for s in samples if 'noise' in s)
            chimera_refined = round(chim / tot_mapped * 100, 2) if tot_mapped else 0.0
    elif has_supp:
        # Segments per mapped read — NOT a fraction of reads, and it can exceed
        # 100% when reads split into 3+ pieces.  Labelled accordingly.
        tot_mapped = sum(s.get('mapped_unfiltered', 0) for s in samples)
        supp = sum(s.get('supplementary_count', 0) for s in samples)
        split_pct = round(supp / tot_mapped * 100, 2) if tot_mapped else 0.0
        split_label = 'Supplementary Segments per Mapped Read'

    # --- EM diagnostics (surfaced so a non-converged run is visible) ---
    em_blocks = [s['em'] for s in samples if 'em' in s]
    em_info = None
    if em_blocks:
        n_reads = sum(b.get('n_reads', 0) for b in em_blocks)
        mass = sum(b.get('counts_total', 0.0) for b in em_blocks)
        em_info = {
            'all_converged': all(b.get('converged') for b in em_blocks),
            'not_converged_samples': [
                s['sample'] for s in samples
                if 'em' in s and not s['em'].get('converged')],
            'max_iterations': max(b.get('iterations', 0) for b in em_blocks),
            'reads': n_reads,
            'mass_assigned': round(mass, 2),
            'mass_conserved': abs(mass - n_reads) < max(1.0, 0.001 * n_reads),
            'reads_unassignable': sum(b.get('reads_unassignable', 0) for b in em_blocks),
        }

    # Reads excluded by the quality filter before the quality/EM pass — proves
    # the read-level pass and the primary table share a read set.
    excluded = sum(s.get('reads_excluded_by_quality_filter', 0) for s in samples)

    return {
        'has_resolution': has_resolution,
        'pct_species': pct_species,
        'mean_support': mean_support,
        'consensus_tau': params.get('consensus_tau', 0.9),
        'split_read_pct': split_pct,
        'split_label': split_label,
        'has_split': split_pct is not None,
        'chimera_rate_refined': chimera_refined,
        'chimera_refined_active': chimera_refined is not None,
        'em': em_info,
        'reads_excluded_by_quality_filter': excluded,
        'quality_pass_reads': tot_reads,
    }


def generate_confusion_html(mapping_data, df_otu=None, top_n=20):
    """HTML table of the taxonomic confusion network aggregated across samples.

    The weight is the number of reads actually CONFOUNDED (i.e. whose consensus
    had a competing taxon carrying real mass), not the OTU's total read count.

    When ``df_otu`` is supplied, the species that OTU was assigned to by PRIMARY
    mapping is shown beside its ID — otherwise the reader has to look up an
    accession|SH code by hand to find out which organism is being confused.
    """
    edges = {}
    for s in mapping_data.get('samples', []):
        tq = s.get('taxonomic_quality')
        if not tq:
            continue
        for edge in tq.get('top_confusion', []):
            key = (edge.get('otu', ''), edge.get('confounder', ''))
            if not key[0] or not key[1]:
                continue
            edges[key] = edges.get(key, 0) + int(edge.get('confounded_reads', 0))
    edges = {k: v for k, v in edges.items() if v > 0}
    if not edges:
        return None

    # OTU_ID -> species assigned by primary mapping
    species_of = {}
    if df_otu is not None and 'Species' in df_otu.columns:
        species_of = (df_otu['Species'].fillna('').astype(str)).to_dict()
        if 'Genus' in df_otu.columns:
            genus = df_otu['Genus'].fillna('').astype(str).to_dict()
            for k, v in list(species_of.items()):
                if not v.strip():
                    species_of[k] = (genus.get(k, '') + ' sp.').strip()

    rows = sorted(edges.items(), key=lambda kv: -kv[1])[:top_n]
    recs = []
    for (otu, conf), n in rows:
        rec = {'OTU': otu}
        if species_of:
            rec['Primary assignment'] = species_of.get(otu, '(not in table)')
        rec['Confounded with'] = conf
        rec['Confounded reads'] = n
        recs.append(rec)
    return pd.DataFrame(recs).to_html(
        classes="table table-striped table-hover table-sm", index=False, border=0)


def generate_lowmapq_html(df_otu, mapq_below=30.0, min_rel_abund=0.01, top_n=10):
    """Screening: OTU abbondanti con MAPQ medio basso — possibile gap di database.

    Calibrazione su 6 mock a composizione nota (TaxQuality_calibrazione.md): le
    metriche di consenso NON distinguono i falsi positivi "concordi" — read che
    concordano con confidenza sulla reference sbagliata perche' quella giusta
    manca dal database (AUROC 0.62-0.78).  mean_mapq pesata per abbondanza li
    separa invece quasi perfettamente (AUROC 0.97): senza la reference vera le
    read si spartiscono fra parenti quasi equivalenti e minimap2 abbassa il
    MAPQ.  Lista di screening ordinata per MAPQ crescente — un aiuto alla
    verifica, non un verdetto.
    """
    if df_otu is None or df_otu.empty or 'mean_mapq' not in df_otu.columns:
        return None
    sample_cols = _sample_columns(df_otu)
    if not sample_cols:
        return None
    counts = df_otu[sample_cols].apply(pd.to_numeric, errors='coerce').fillna(0)
    tot = counts.sum(axis=1)
    grand = float(tot.sum())
    if grand <= 0:
        return None
    rel = tot / grand
    mapq = pd.to_numeric(df_otu['mean_mapq'], errors='coerce')
    mask = (rel >= min_rel_abund) & mapq.notna() & (mapq < mapq_below)
    if not mask.any():
        return None
    sel = df_otu[mask]
    disp = pd.DataFrame({
        'Species': sel['Species'].fillna('') if 'Species' in sel.columns else '',
        'Reads': tot[mask].astype(int),
        'Rel. abundance (%)': (rel[mask] * 100).round(2),
        'Mean MAPQ': mapq[mask].round(1),
        'pct_species': pd.to_numeric(sel.get('pct_species'), errors='coerce').round(1),
        'mean_support': pd.to_numeric(sel.get('mean_support'), errors='coerce').round(2),
    }, index=sel.index)
    disp.index.name = 'OTU_ID'
    disp = disp.sort_values('Mean MAPQ').head(top_n)
    return disp.to_html(classes="table table-striped table-hover table-sm",
                        index=True, border=0)


def generate_mapping_graphs(mapping_data):
    """Generate mapping QC bar charts: mapped/unmapped per sample and quality filter retention."""
    samples_list = mapping_data.get('samples', [])
    if not samples_list:
        return None, None

    df = pd.DataFrame(samples_list)

    # Chart 1: Mapped vs unmapped reads per sample
    df['unmapped'] = df['total_reads'] - df['mapped_unfiltered']
    df_long = df.melt(
        id_vars=['sample'],
        value_vars=['mapped_unfiltered', 'unmapped'],
        var_name='Read Type', value_name='Reads'
    )
    df_long['Read Type'] = df_long['Read Type'].replace({
        'mapped_unfiltered': 'Mapped', 'unmapped': 'Unmapped'
    })
    fig_mapping = px.bar(
        df_long, x='sample', y='Reads', color='Read Type',
        title='Mapping Results per Sample (Mapped vs. Unmapped)',
        labels={'sample': 'Sample', 'Reads': 'Number of Reads'},
        color_discrete_map={'Mapped': '#1f77b4', 'Unmapped': '#aec7e8'},
        barmode='stack'
    )
    fig_mapping_div = pio.to_html(fig_mapping, full_html=False, include_plotlyjs='cdn')

    # Chart 2: Quality filter retention (only if quality filter was active)
    params = mapping_data.get('parameters', {})
    quality_filter_active = params.get('min_percent_identity', 0) > 0 or params.get('min_ref_coverage', 0) > 0
    fig_quality_div = None
    if quality_filter_active and 'mapped_filtered' in df.columns:
        df['reads_removed_by_filter'] = df['mapped_unfiltered'] - df['mapped_filtered']
        df_qlong = df.melt(
            id_vars=['sample'],
            value_vars=['mapped_filtered', 'reads_removed_by_filter'],
            var_name='Category', value_name='Reads'
        )
        df_qlong['Category'] = df_qlong['Category'].replace({
            'mapped_filtered': 'Passed Quality Filter',
            'reads_removed_by_filter': 'Removed by Quality Filter'
        })
        title_parts = []
        if params.get('min_percent_identity', 0) > 0:
            title_parts.append(f"Identity ≥ {params['min_percent_identity']}%")
        if params.get('min_ref_coverage', 0) > 0:
            title_parts.append(f"Ref Coverage ≥ {params['min_ref_coverage']}%")
        filter_desc = " | ".join(title_parts)
        fig_quality = px.bar(
            df_qlong, x='sample', y='Reads', color='Category',
            title=f'Alignment Quality Filter per Sample ({filter_desc})',
            labels={'sample': 'Sample', 'Reads': 'Mapped Reads'},
            color_discrete_map={
                'Passed Quality Filter': '#2ca02c',
                'Removed by Quality Filter': '#d62728'
            },
            barmode='stack'
        )
        fig_quality_div = pio.to_html(fig_quality, full_html=False, include_plotlyjs=False)

    return fig_mapping_div, fig_quality_div


def generate_mapping_table_html(mapping_data):
    """Generate per-sample mapping stats HTML table."""
    samples_list = mapping_data.get('samples', [])
    if not samples_list:
        return None
    df = pd.DataFrame(samples_list)
    params = mapping_data.get('parameters', {})
    quality_filter_active = params.get('min_percent_identity', 0) > 0 or params.get('min_ref_coverage', 0) > 0

    cols = ['sample', 'total_reads', 'mapped_unfiltered', 'mapping_rate_pct']
    rename = {
        'sample': 'Sample', 'total_reads': 'Total Reads',
        'mapped_unfiltered': 'Mapped Reads', 'mapping_rate_pct': 'Mapping Rate (%)',
    }
    if quality_filter_active:
        cols += ['mapped_filtered', 'quality_retention_pct']
        rename.update({
            'mapped_filtered': 'Reads After Quality Filter',
            'quality_retention_pct': 'Quality Retention (%)'
        })
    df_display = df[cols].rename(columns=rename)
    return df_display.to_html(
        classes="table table-striped table-hover table-sm",
        index=False, border=0
    )


def load_data(filter_path, otu_path):
    # OPT-7: Support both TSV and XLSX filter reports
    print(f"Loading filter data from: {filter_path}")
    fp = Path(filter_path)
    try:
        if fp.suffix == '.tsv':
            df_filter = pd.read_csv(filter_path, sep='\t')
        elif fp.suffix == '.xlsx':
            df_filter = pd.read_excel(filter_path)
        else:
            # Try TSV first, fall back to Excel
            try:
                df_filter = pd.read_csv(filter_path, sep='\t')
            except Exception:
                df_filter = pd.read_excel(filter_path)
    except Exception as e:
        print(f"ERROR: Cannot read filter file: {e}", file=sys.stderr)
        sys.exit(1)

    # OPT-A5: Prefer TSV (faster to load) over XLSX when available
    otu_path_obj = Path(otu_path)
    tsv_otu_path = otu_path_obj.with_suffix('.tsv')
    print(f"Loading OTU table from: {otu_path}")
    try:
        if tsv_otu_path.exists():
            print(f"  (Using TSV format: {tsv_otu_path.name})")
            df_otu = pd.read_csv(tsv_otu_path, sep='\t', index_col=0)
        else:
            df_otu = pd.read_excel(otu_path, index_col=0)
    except FileNotFoundError:
        print(f"WARNING: OTU file not found: {otu_path}. "
              "Report will be generated without metagenomic section.")
        df_otu = pd.DataFrame(columns=['Taxonomy'])
        df_otu.index.name = 'OTU_ID'
    except Exception as e:
        print(f"ERROR: Cannot read OTU file: {e}", file=sys.stderr)
        sys.exit(1)
    return df_filter, df_otu


def get_kpis(df_filter, df_otu):
    print("Calculating KPIs...")
    total_seq = df_filter['total count'].sum()
    good_seq = df_filter['good count'].sum()
    if total_seq > 0:
        rejection_rate = f"{(total_seq - good_seq) / total_seq:.1%}"
    else:
        rejection_rate = "N/A"
    otu_count = len(df_otu) if not df_otu.empty else 0
    kpis = {
        'total_sequences': f"{total_seq:,}",
        'good_sequences': f"{good_seq:,}",
        'rejection_rate': rejection_rate,
        'otus_found': f"{otu_count:,}",
        'samples_processed': len(df_filter),
        'has_otu_data': otu_count > 0,
    }
    return kpis


def generate_filter_graphs(df_filter):
    print("Generating filter graphs...")
    df_filter_long = df_filter.melt(
        id_vars=['barcode'],
        value_vars=['good count', 'bad count'],
        var_name='Count Type',
        value_name='Sequences'
    )
    fig_counts = px.bar(
        df_filter_long, x='barcode', y='Sequences', color='Count Type',
        title="Filter Count Report (Good vs. Bad)",
        color_discrete_map={'good count': '#2ca02c', 'bad count': '#d62728'}
    )
    fig_counts_div = pio.to_html(fig_counts, full_html=False, include_plotlyjs='cdn')
    fig_lengths = px.bar(
        df_filter, x='barcode', y='mean length',
        title='Mean Sequence Length (post-filter)',
        labels={'mean length': 'Mean Length (bp)'}
    )
    fig_lengths.add_trace(go.Scatter(
        x=df_filter['barcode'], y=df_filter['median length'],
        mode='markers', name='Median Length',
        marker=dict(color='black', size=8)
    ))
    fig_lengths_div = pio.to_html(fig_lengths, full_html=False, include_plotlyjs=False)
    return fig_counts_div, fig_lengths_div


# ---------------------------------------------------------------------------
# OPT-9: Taxonomy rank extraction (uses pre-split columns when available)
# ---------------------------------------------------------------------------

# Column names produced by the split in ResultsReader
_RANK_COLUMNS = ['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species', 'Details']

# Per-OTU taxonomic-quality columns (Feature A).  These are METADATA and must
# never be mistaken for sample abundance columns: doing so added them to the
# composition chart's sample list and, because `qual_n_reads` is itself a read
# count, inflated per-OTU row totals non-uniformly, biasing the top-25 heatmap
# ranking and the Sankey. Imported from ResultsReader so the two cannot drift.
try:
    from ResultsReader import QUALITY_COLUMNS as _QUALITY_COLUMNS
except Exception:  # pragma: no cover - report can run standalone
    _QUALITY_COLUMNS = [
        'pct_species', 'pct_genus', 'pct_above_genus', 'pct_unresolved',
        'resolution_rank', 'resolution_depth_mode', 'mean_support',
        'mean_mapq', 'top_confounder', 'confounded_reads', 'qual_n_reads']

# Everything that is not an abundance column.
_META_COLUMNS = {'Taxonomy'} | set(_RANK_COLUMNS) | set(_QUALITY_COLUMNS)


def _sample_columns(df_otu):
    """Abundance (sample) columns of an OTU table, excluding all metadata."""
    return [c for c in df_otu.columns if c not in _META_COLUMNS]


def _extract_ranks_vectorized(df_otu, sample_cols):
    """Extract Family/Genus/Species for all rows.

    If the OTU table already contains the pre-split rank columns
    (Kingdom … Details), use them directly.  Otherwise fall back to
    the legacy semicolon-split approach for backward compatibility.
    """
    ranks = {}
    pre_split = all(col in df_otu.columns for col in ('Family', 'Genus', 'Species'))

    if pre_split:
        # --- New path: use pre-split columns directly ---
        for rank_name in ('Family', 'Genus', 'Species'):
            ranks[rank_name] = (
                df_otu[rank_name]
                .fillna('')
                .replace('', 'Unclassified')
            )
    else:
        # --- Legacy fallback: parse the Taxonomy string ---
        tax_series = df_otu['Taxonomy'].fillna('')

        def _clean_split(tax_str):
            if not isinstance(tax_str, str):
                return []
            return [p for p in tax_str.split(';')
                    if p and not p.lower().startswith('unclassified')]

        split_lists = tax_series.apply(_clean_split)

        def _get_rank(parts_list, position):
            try:
                if len(parts_list) >= abs(position):
                    return parts_list[position]
            except (IndexError, TypeError):
                pass
            return 'Unclassified'

        for rank_name, pos in [('Family', -3), ('Genus', -2), ('Species', -1)]:
            ranks[rank_name] = split_lists.apply(
                lambda p, po=pos: _get_rank(p, po)
            )

    return ranks


def aggregate_by_rank(df_otu, sample_cols, rank_col, rank_name, top_n=15):
    """Aggregate OTU counts by a pre-computed rank column."""
    print(f"Aggregating for {rank_name}...")

    df_agg = df_otu.groupby(rank_col)[sample_cols].sum()
    df_agg['Total'] = df_agg.sum(axis=1)
    df_agg = df_agg.sort_values(by='Total', ascending=False)

    if len(df_agg) > top_n:
        df_top = df_agg.head(top_n - 1)
        df_others = df_agg.tail(len(df_agg) - (top_n - 1)).sum().to_frame().T
        df_others.index = [f'Others ({rank_name})']
        df_agg = pd.concat([df_top, df_others])

    df_agg = df_agg.drop(columns='Total')
    df_rel = df_agg.div(df_agg.sum(axis=0), axis=1) * 100
    df_rel.index.name = rank_name

    df_long = df_rel.reset_index().melt(
        id_vars=rank_name,
        var_name='Sample',
        value_name='Relative Abundance (%)'
    )
    df_long = df_long.rename(columns={rank_name: 'Taxonomy'})
    df_long['Rank'] = rank_name
    return df_long


def generate_sankey(df_otu):
    """Build Sankey data with per-row lineage information for interactive filtering.

    Returns a JSON string containing:
      - lineages: list of {Kingdom, Phylum, ..., Species, count} per OTU row
      - rankColors: color mapping per rank level
    The actual Sankey rendering and filtering is done in JavaScript (template.html).
    Returns None if no valid data.
    """
    print("Generating Lineages Sankey data...")

    # Determine which rank columns are available
    sankey_ranks = ['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']
    pre_split = all(r in df_otu.columns for r in sankey_ranks)

    sample_cols = _sample_columns(df_otu)

    if pre_split:
        rank_series = {r: df_otu[r].fillna('').replace('', 'Unclassified') for r in sankey_ranks}
    elif 'Taxonomy' in df_otu.columns:
        tax_parts = df_otu['Taxonomy'].fillna('').apply(
            lambda t: [p.strip().replace('_', ' ') for p in t.split(';') if p.strip()] if isinstance(t, str) else []
        )
        rank_series = {}
        for idx, rank in enumerate(sankey_ranks):
            rank_series[rank] = tax_parts.apply(
                lambda p, i=idx: p[i] if len(p) > i else 'Unclassified'
            )
    else:
        return None

    # Compute total counts per OTU row
    counts = df_otu[sample_cols].apply(pd.to_numeric, errors='coerce').fillna(0).sum(axis=1)

    # Build per-row lineage records (one per OTU)
    lineages = []
    for idx in df_otu.index:
        row_count = int(counts.get(idx, 0))
        if row_count <= 0:
            continue
        record = {rank: rank_series[rank].get(idx, 'Unclassified') for rank in sankey_ranks}
        # Skip rows where all ranks are unclassified
        if all(v == 'Unclassified' for v in record.values()):
            continue
        record['count'] = row_count
        lineages.append(record)

    if not lineages:
        print("WARNING: No valid lineage data found for Sankey.", file=sys.stderr)
        return None

    rank_colors = {
        'Kingdom': 'rgba(31,119,180,0.7)',
        'Phylum':  'rgba(255,127,14,0.7)',
        'Class':   'rgba(44,160,44,0.7)',
        'Order':   'rgba(214,39,40,0.7)',
        'Family':  'rgba(148,103,189,0.7)',
        'Genus':   'rgba(140,86,75,0.7)',
        'Species': 'rgba(227,119,194,0.7)',
    }

    sankey_data = {
        'lineages': lineages,
        'ranks': sankey_ranks,
        'rankColors': rank_colors,
    }

    return json.dumps(sankey_data)


def build_composition_json(df_otu):
    """Family/Genus/Species relative-abundance records for one OTU table.

    Factored out of generate_otu_data_json so the EM table can be rendered
    through exactly the same aggregation path as the primary table — otherwise
    the two series in the comparison view would not be like-for-like."""
    if df_otu is None or df_otu.empty:
        return None
    has_tax = 'Taxonomy' in df_otu.columns or 'Family' in df_otu.columns
    if not has_tax:
        return None
    sample_cols = _sample_columns(df_otu)
    if not sample_cols:
        return None
    df = df_otu.copy()
    df[sample_cols] = df[sample_cols].apply(pd.to_numeric, errors='coerce').fillna(0)
    ranks = _extract_ranks_vectorized(df, sample_cols)
    parts = [
        aggregate_by_rank(df, sample_cols, ranks['Family'], 'Family', top_n=20),
        aggregate_by_rank(df, sample_cols, ranks['Genus'], 'Genus', top_n=15),
        aggregate_by_rank(df, sample_cols, ranks['Species'], 'Species', top_n=15),
    ]
    return pd.concat(parts, ignore_index=True).to_json(orient='records')


def generate_otu_data_json(df_otu):
    print("Generating taxonomic data (Family, Genus, Species)...")

    # Check for taxonomy data (either single column or pre-split columns)
    has_taxonomy = 'Taxonomy' in df_otu.columns or 'Family' in df_otu.columns
    if not has_taxonomy:
        print("WARNING: No taxonomy columns found. Skipping OTU graphs.", file=sys.stderr)
        return "null", None

    # Exclude all taxonomy/quality metadata columns from sample columns
    sample_cols = _sample_columns(df_otu)

    # Ensure sample columns are numeric (DuckDB/XLSX can leave object dtype)
    df_otu[sample_cols] = df_otu[sample_cols].apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)

    # OPT-9: Single-pass taxonomy extraction for all ranks
    ranks = _extract_ranks_vectorized(df_otu, sample_cols)

    df_family = aggregate_by_rank(df_otu, sample_cols, ranks['Family'], 'Family', top_n=20)
    df_genus = aggregate_by_rank(df_otu, sample_cols, ranks['Genus'], 'Genus', top_n=15)
    df_species = aggregate_by_rank(df_otu, sample_cols, ranks['Species'], 'Species', top_n=15)

    df_all_ranks = pd.concat([df_family, df_genus, df_species], ignore_index=True)

    composition_json_data = df_all_ranks.to_json(orient='records')

    print("Generating Heatmap graph...")
    df_counts_only = df_otu[sample_cols]
    top_25_otus = df_counts_only.sum(axis=1).nlargest(25).index
    df_top25 = df_counts_only.loc[top_25_otus]
    df_top25_log = np.log1p(df_top25)

    # Use Species names as Y-axis labels instead of OTU IDs
    if 'Species' in df_otu.columns:
        species_labels = df_otu.loc[top_25_otus, 'Species'].fillna('').replace('', 'Unknown')
        # Disambiguate duplicate species by appending OTU ID
        seen = {}
        y_labels = []
        for otu_id, sp in zip(top_25_otus, species_labels):
            seen[sp] = seen.get(sp, 0) + 1
            if seen[sp] > 1:
                y_labels.append(f"{sp} ({otu_id})")
            else:
                y_labels.append(sp)
        # Second pass: also tag the first occurrence if duplicated
        for i, sp in enumerate(species_labels):
            if seen[sp] > 1 and '(' not in y_labels[i]:
                y_labels[i] = f"{sp} ({top_25_otus[i]})"
    else:
        y_labels = list(top_25_otus)

    fig_heatmap = px.imshow(
        df_top25_log, title="Top 25 Species Heatmap (Log-normalized Abundance)",
        labels=dict(x="Sample", y="Species", color="Log(Count+1)"),
        x=df_top25_log.columns, y=y_labels,
        aspect="auto", height=700
    )
    fig_heatmap_div = pio.to_html(fig_heatmap, full_html=False, include_plotlyjs=False)

    return composition_json_data, fig_heatmap_div


def generate_em_comparison_html(otu_path, em_path, top_n=25):
    """Compare primary counts against EM fractional counts per OTU.

    Surfaces what the EM actually changed — without this the _EM table was
    written to disk and never referenced anywhere in the report."""
    if not em_path:
        return None, None
    em_p = Path(em_path)
    em_tsv = em_p.with_suffix('.tsv')
    src = em_tsv if em_tsv.exists() else em_p
    if not src.exists():
        return None, None
    try:
        df_em = (pd.read_csv(src, sep='\t', index_col=0) if src.suffix == '.tsv'
                 else pd.read_excel(src, index_col=0))
        otu_p = Path(otu_path)
        otu_tsv = otu_p.with_suffix('.tsv')
        osrc = otu_tsv if otu_tsv.exists() else otu_p
        df_pr = (pd.read_csv(osrc, sep='\t', index_col=0) if osrc.suffix == '.tsv'
                 else pd.read_excel(osrc, index_col=0))
    except Exception as e:
        print(f"WARNING: cannot read EM comparison tables: {e}", file=sys.stderr)
        return None, None

    sc_em = _sample_columns(df_em)
    sc_pr = _sample_columns(df_pr)
    if not sc_em or not sc_pr:
        return None, None

    prim = df_pr[sc_pr].apply(pd.to_numeric, errors='coerce').fillna(0).sum(axis=1)
    emc = df_em[sc_em].apply(pd.to_numeric, errors='coerce').fillna(0).sum(axis=1)
    comp = pd.DataFrame({'Primary count': prim, 'EM count': emc}).fillna(0)
    comp['Shift'] = comp['EM count'] - comp['Primary count']
    label_col = 'Species' if 'Species' in df_pr.columns else None
    if label_col is not None:
        comp.insert(0, 'Species', df_pr[label_col].reindex(comp.index).fillna(''))

    totals = {
        'primary_total': float(prim.sum()),
        'em_total': float(emc.sum()),
        'n_otu_primary': int((prim > 0).sum()),
        'n_otu_em': int((emc > 0).sum()),
        'moved': float(comp['Shift'].abs().sum() / 2.0),
        'moved_pct': (round(comp['Shift'].abs().sum() / 2.0 / prim.sum() * 100, 2)
                      if prim.sum() else 0.0),
    }

    shown = comp.reindex(comp['Shift'].abs().sort_values(ascending=False).index).head(top_n)
    shown = shown[shown['Shift'].abs() > 1e-9]
    if shown.empty:
        return None, totals
    for c in ('Primary count', 'EM count', 'Shift'):
        shown[c] = shown[c].round(2)
    return shown.to_html(classes="table table-striped table-hover table-sm",
                         border=0), totals


def main():
    options = parse_arguments()

    filter_report_path = Path(options.filter_report)
    otu_table_path = Path(options.otu_table)
    output_html_path = Path(options.output_html)
    template_file = Path(__file__).parent / "template.html"

    if not template_file.exists():
        print("ERROR: 'template.html' file not found.", file=sys.stderr)
        sys.exit(1)

    # OPT-7: Try TSV first (new format), fallback to XLSX (old format)
    if not filter_report_path.exists():
        # Check if the TSV version exists (pipeline now writes .tsv)
        tsv_path = filter_report_path.with_suffix('.tsv')
        xlsx_path = filter_report_path.with_suffix('.xlsx')
        if tsv_path.exists():
            filter_report_path = tsv_path
        elif xlsx_path.exists():
            filter_report_path = xlsx_path

    df_filter, df_otu = load_data(filter_report_path, otu_table_path)
    kpis = get_kpis(df_filter, df_otu)
    graph_filter_counts_div, graph_filter_lengths_div = generate_filter_graphs(df_filter)

    # OTU / Metagenomic section (skipped when OTU table is empty)
    has_otu_data = not df_otu.empty
    if has_otu_data:
        composition_json_data, graph_otu_heatmap_div = generate_otu_data_json(df_otu)
        sankey_json_data = generate_sankey(df_otu)
    else:
        print("WARNING: OTU table is empty — skipping metagenomic graphs.")
        composition_json_data, graph_otu_heatmap_div = "null", None
        sankey_json_data = None

    # Mapping QC section (optional)
    mapping_data, _ = load_mapping_stats(options.mapping_stats)
    mapping_kpis = get_mapping_kpis(mapping_data) if mapping_data else None

    # Analysis parameters summary (length + quality filters)
    analysis_params = extract_filter_params(
        filter_report_path, options.min_len, options.max_len, mapping_data
    )
    if mapping_data:
        graph_mapping_div, graph_quality_div = generate_mapping_graphs(mapping_data)
        table_mapping_html = generate_mapping_table_html(mapping_data)
        taxq_kpis = get_taxquality_kpis(mapping_data)
        table_confusion_html = generate_confusion_html(mapping_data, df_otu)
        table_lowmapq_html = generate_lowmapq_html(df_otu)
    else:
        graph_mapping_div = graph_quality_div = table_mapping_html = None
        taxq_kpis = table_confusion_html = None
        table_lowmapq_html = None

    table_em_html, em_totals = generate_em_comparison_html(
        otu_table_path, options.otu_table_em)

    # Composition of the EM table, for the abundance-source selector.
    composition_json_data_em = "null"
    if options.otu_table_em:
        _emp = Path(options.otu_table_em)
        _emsrc = _emp.with_suffix('.tsv') if _emp.with_suffix('.tsv').exists() else _emp
        if _emsrc.exists():
            try:
                _df_em = (pd.read_csv(_emsrc, sep='\t', index_col=0)
                          if _emsrc.suffix == '.tsv'
                          else pd.read_excel(_emsrc, index_col=0))
                composition_json_data_em = build_composition_json(_df_em) or "null"
            except Exception as e:
                print(f"WARNING: cannot build EM composition: {e}", file=sys.stderr)

    print("Converting tables to HTML...")
    table_filter_html = df_filter.to_html(
        classes="table table-striped table-hover table-sm",
        index=False, border=0
    )

    # OPT-10: Limit OTU HTML table to top 500 rows (full table is in XLSX)
    # Show only OTU_ID (index), Species, and sample abundance columns
    if has_otu_data:
        total_otu_rows = len(df_otu)
        sample_cols = _sample_columns(df_otu)

        # Build a simplified display DataFrame: Species + sample columns only
        display_cols = []
        if 'Species' in df_otu.columns:
            display_cols.append('Species')
        display_cols.extend(sample_cols)

        if total_otu_rows > 500:
            # Sort by total abundance and take top 500
            df_otu_sorted = df_otu.copy()
            df_otu_sorted['_total'] = df_otu_sorted[sample_cols].sum(axis=1)
            df_otu_sorted = df_otu_sorted.sort_values('_total', ascending=False)
            df_otu_display = df_otu_sorted.head(500)[display_cols]
            table_otu_html = df_otu_display.to_html(
                classes="table table-striped table-hover table-sm",
                index=True, border=0, table_id="otu-table"
            )
            table_otu_html += (
                f'<div class="alert alert-info mt-2">'
                f'<small>Showing top 500 of {total_otu_rows:,} OTUs by abundance. '
                f'Full table available in the XLSX file.</small></div>'
            )
            print(f"OTU table limited to 500/{total_otu_rows} rows for HTML.")
        else:
            table_otu_html = df_otu[display_cols].to_html(
                classes="table table-striped table-hover table-sm",
                index=True, border=0, table_id="otu-table"
            )
    else:
        table_otu_html = None

    print("Rendering final HTML report...")
    template_loader = jinja2.FileSystemLoader(searchpath=Path(__file__).parent)
    template_env = jinja2.Environment(loader=template_loader)
    template = template_env.get_template(template_file.name)

    context = {
        "project_name": options.project_name,
        "report_date": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "kpis": kpis,
        "graph_filter_counts_div": graph_filter_counts_div,
        "graph_filter_lengths_div": graph_filter_lengths_div,
        "table_filter_html": table_filter_html,
        "composition_json_data": composition_json_data,
        "graph_otu_heatmap_div": graph_otu_heatmap_div,
        "sankey_json_data": sankey_json_data if sankey_json_data else "null",
        "table_otu_html": table_otu_html,
        "mapping_kpis": mapping_kpis,
        "graph_mapping_div": graph_mapping_div,
        "graph_quality_div": graph_quality_div,
        "table_mapping_html": table_mapping_html,
        "taxq_kpis": taxq_kpis,
        "table_confusion_html": table_confusion_html,
        "table_lowmapq_html": table_lowmapq_html,
        "table_em_html": table_em_html,
        "em_totals": em_totals,
        "composition_json_data_em": composition_json_data_em,
        "analysis_params": analysis_params,
    }

    try:
        html_content = template.render(context)
        with open(output_html_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        print(f"\n--- HTML Report Generated Successfully! ---")
        print(f"Open this file in your browser: {output_html_path.resolve()}")

    except Exception as e:
        print(f"ERROR during template rendering: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
