#!/usr/bin/env python3

import pandas as pd
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
import jinja2
import numpy as np
from pathlib import Path
import sys
import argparse
import datetime
import json


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Interactive HTML Report Generator for OTU Pipeline."
    )
    parser.add_argument(
        "-f", "--filter_report",
        help="Path to filter report (TSV or XLSX)",
        required=True, type=str
    )
    parser.add_argument(
        "-otu", "--otu_table",
        help="Path to Excel file 'Final_OTU_Table.xlsx'",
        required=True, type=str
    )
    parser.add_argument(
        "-o", "--output_html",
        help="Path for output HTML file (e.g., 'MyReport.html').",
        required=True, type=str
    )
    parser.add_argument(
        "-pn", "--project_name",
        help="[Optional] Project name to display on report.",
        type=str, default="Metagenomic Analysis Report"
    )
    parser.add_argument(
        "-ms", "--mapping_stats",
        help="[Optional] Path to mapping_stats.json generated by the pipeline.",
        type=str, default=None
    )
    return parser.parse_args()


def load_mapping_stats(mapping_stats_path):
    """Load mapping_stats.json if present, return (stats_dict, error_msg)."""
    if not mapping_stats_path:
        return None, None
    try:
        with open(mapping_stats_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(f"Mapping stats loaded from: {mapping_stats_path}")
        return data, None
    except Exception as e:
        msg = f"WARNING: Cannot read mapping stats file: {e}"
        print(msg, file=sys.stderr)
        return None, msg


def get_mapping_kpis(mapping_data):
    """Compute mapping KPI cards from mapping_stats dict."""
    summary = mapping_data.get('summary', {})
    params = mapping_data.get('parameters', {})
    total = summary.get('total_reads_all', 0)
    mapped = summary.get('total_mapped_all', 0)
    filtered = summary.get('total_after_quality_filter', 0)
    mapping_rate = summary.get('overall_mapping_rate_pct', 0.0)
    retention = summary.get('overall_quality_retention_pct', 100.0)
    min_id = params.get('min_percent_identity', 0.0)
    min_cov = params.get('min_ref_coverage', 0.0)
    quality_filter_active = min_id > 0 or min_cov > 0
    return {
        'total_reads': f"{total:,}",
        'mapped_reads': f"{mapped:,}",
        'mapping_rate': f"{mapping_rate:.1f}%",
        'reads_after_quality_filter': f"{filtered:,}",
        'quality_retention': f"{retention:.1f}%",
        'quality_filter_active': quality_filter_active,
        'min_percent_identity': min_id,
        'min_ref_coverage': min_cov,
    }


def generate_mapping_graphs(mapping_data):
    """Generate mapping QC bar charts: mapped/unmapped per sample and quality filter retention."""
    samples_list = mapping_data.get('samples', [])
    if not samples_list:
        return None, None

    df = pd.DataFrame(samples_list)

    # Chart 1: Mapped vs unmapped reads per sample
    df['unmapped'] = df['total_reads'] - df['mapped_unfiltered']
    df_long = df.melt(
        id_vars=['sample'],
        value_vars=['mapped_unfiltered', 'unmapped'],
        var_name='Read Type', value_name='Reads'
    )
    df_long['Read Type'] = df_long['Read Type'].replace({
        'mapped_unfiltered': 'Mapped', 'unmapped': 'Unmapped'
    })
    fig_mapping = px.bar(
        df_long, x='sample', y='Reads', color='Read Type',
        title='Mapping Results per Sample (Mapped vs. Unmapped)',
        labels={'sample': 'Sample', 'Reads': 'Number of Reads'},
        color_discrete_map={'Mapped': '#1f77b4', 'Unmapped': '#aec7e8'},
        barmode='stack'
    )
    fig_mapping_div = pio.to_html(fig_mapping, full_html=False, include_plotlyjs='cdn')

    # Chart 2: Quality filter retention (only if quality filter was active)
    params = mapping_data.get('parameters', {})
    quality_filter_active = params.get('min_percent_identity', 0) > 0 or params.get('min_ref_coverage', 0) > 0
    fig_quality_div = None
    if quality_filter_active and 'mapped_filtered' in df.columns:
        df['reads_removed_by_filter'] = df['mapped_unfiltered'] - df['mapped_filtered']
        df_qlong = df.melt(
            id_vars=['sample'],
            value_vars=['mapped_filtered', 'reads_removed_by_filter'],
            var_name='Category', value_name='Reads'
        )
        df_qlong['Category'] = df_qlong['Category'].replace({
            'mapped_filtered': 'Passed Quality Filter',
            'reads_removed_by_filter': 'Removed by Quality Filter'
        })
        title_parts = []
        if params.get('min_percent_identity', 0) > 0:
            title_parts.append(f"Identity ≥ {params['min_percent_identity']}%")
        if params.get('min_ref_coverage', 0) > 0:
            title_parts.append(f"Ref Coverage ≥ {params['min_ref_coverage']}%")
        filter_desc = " | ".join(title_parts)
        fig_quality = px.bar(
            df_qlong, x='sample', y='Reads', color='Category',
            title=f'Alignment Quality Filter per Sample ({filter_desc})',
            labels={'sample': 'Sample', 'Reads': 'Mapped Reads'},
            color_discrete_map={
                'Passed Quality Filter': '#2ca02c',
                'Removed by Quality Filter': '#d62728'
            },
            barmode='stack'
        )
        fig_quality_div = pio.to_html(fig_quality, full_html=False, include_plotlyjs=False)

    return fig_mapping_div, fig_quality_div


def generate_mapping_table_html(mapping_data):
    """Generate per-sample mapping stats HTML table."""
    samples_list = mapping_data.get('samples', [])
    if not samples_list:
        return None
    df = pd.DataFrame(samples_list)
    params = mapping_data.get('parameters', {})
    quality_filter_active = params.get('min_percent_identity', 0) > 0 or params.get('min_ref_coverage', 0) > 0

    cols = ['sample', 'total_reads', 'mapped_unfiltered', 'mapping_rate_pct']
    rename = {
        'sample': 'Sample', 'total_reads': 'Total Reads',
        'mapped_unfiltered': 'Mapped Reads', 'mapping_rate_pct': 'Mapping Rate (%)',
    }
    if quality_filter_active:
        cols += ['mapped_filtered', 'quality_retention_pct']
        rename.update({
            'mapped_filtered': 'Reads After Quality Filter',
            'quality_retention_pct': 'Quality Retention (%)'
        })
    df_display = df[cols].rename(columns=rename)
    return df_display.to_html(
        classes="table table-striped table-hover table-sm",
        index=False, border=0
    )


def load_data(filter_path, otu_path):
    # OPT-7: Support both TSV and XLSX filter reports
    print(f"Loading filter data from: {filter_path}")
    fp = Path(filter_path)
    try:
        if fp.suffix == '.tsv':
            df_filter = pd.read_csv(filter_path, sep='\t')
        elif fp.suffix == '.xlsx':
            df_filter = pd.read_excel(filter_path)
        else:
            # Try TSV first, fall back to Excel
            try:
                df_filter = pd.read_csv(filter_path, sep='\t')
            except Exception:
                df_filter = pd.read_excel(filter_path)
    except Exception as e:
        print(f"ERROR: Cannot read filter file: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading OTU table from: {otu_path}")
    try:
        df_otu = pd.read_excel(otu_path, index_col=0)
    except FileNotFoundError:
        print(f"WARNING: OTU file not found: {otu_path}. "
              "Report will be generated without metagenomic section.")
        df_otu = pd.DataFrame(columns=['Taxonomy'])
        df_otu.index.name = 'OTU_ID'
    except Exception as e:
        print(f"ERROR: Cannot read OTU file: {e}", file=sys.stderr)
        sys.exit(1)
    return df_filter, df_otu


def get_kpis(df_filter, df_otu):
    print("Calculating KPIs...")
    total_seq = df_filter['total count'].sum()
    good_seq = df_filter['good count'].sum()
    if total_seq > 0:
        rejection_rate = f"{(total_seq - good_seq) / total_seq:.1%}"
    else:
        rejection_rate = "N/A"
    otu_count = len(df_otu) if not df_otu.empty else 0
    kpis = {
        'total_sequences': f"{total_seq:,}",
        'good_sequences': f"{good_seq:,}",
        'rejection_rate': rejection_rate,
        'otus_found': f"{otu_count:,}",
        'samples_processed': len(df_filter),
        'has_otu_data': otu_count > 0,
    }
    return kpis


def generate_filter_graphs(df_filter):
    print("Generating filter graphs...")
    df_filter_long = df_filter.melt(
        id_vars=['barcode'],
        value_vars=['good count', 'bad count'],
        var_name='Count Type',
        value_name='Sequences'
    )
    fig_counts = px.bar(
        df_filter_long, x='barcode', y='Sequences', color='Count Type',
        title="Filter Count Report (Good vs. Bad)",
        color_discrete_map={'good count': '#2ca02c', 'bad count': '#d62728'}
    )
    fig_counts_div = pio.to_html(fig_counts, full_html=False, include_plotlyjs='cdn')
    fig_lengths = px.bar(
        df_filter, x='barcode', y='mean length',
        title='Mean Sequence Length (post-filter)',
        labels={'mean length': 'Mean Length (bp)'}
    )
    fig_lengths.add_trace(go.Scatter(
        x=df_filter['barcode'], y=df_filter['median length'],
        mode='markers', name='Median Length',
        marker=dict(color='black', size=8)
    ))
    fig_lengths_div = pio.to_html(fig_lengths, full_html=False, include_plotlyjs=False)
    return fig_counts_div, fig_lengths_div


# ---------------------------------------------------------------------------
# OPT-9: Vectorized taxonomy aggregation (single-pass split)
# ---------------------------------------------------------------------------

def _extract_ranks_vectorized(df_otu, sample_cols):
    """Split Taxonomy once, extract Family/Genus/Species for all rows."""
    tax_series = df_otu['Taxonomy'].fillna('')

    # Split by ';' and filter out empty and 'unclassified' parts per row
    def _clean_split(tax_str):
        if not isinstance(tax_str, str):
            return []
        parts = [p for p in tax_str.split(';') if p and not p.lower().startswith('unclassified')]
        return parts

    split_lists = tax_series.apply(_clean_split)

    def _get_rank(parts_list, position):
        try:
            if len(parts_list) >= abs(position):
                return parts_list[position]
        except (IndexError, TypeError):
            pass
        return 'Unclassified'

    ranks = {}
    for rank_name, pos in [('Family', -3), ('Genus', -2), ('Species', -1)]:
        ranks[rank_name] = split_lists.apply(lambda p, po=pos: _get_rank(p, po))

    return ranks


def aggregate_by_rank(df_otu, sample_cols, rank_col, rank_name, top_n=15):
    """Aggregate OTU counts by a pre-computed rank column."""
    print(f"Aggregating for {rank_name}...")

    df_agg = df_otu.groupby(rank_col)[sample_cols].sum()
    df_agg['Total'] = df_agg.sum(axis=1)
    df_agg = df_agg.sort_values(by='Total', ascending=False)

    if len(df_agg) > top_n:
        df_top = df_agg.head(top_n - 1)
        df_others = df_agg.tail(len(df_agg) - (top_n - 1)).sum().to_frame().T
        df_others.index = [f'Others ({rank_name})']
        df_agg = pd.concat([df_top, df_others])

    df_agg = df_agg.drop(columns='Total')
    df_rel = df_agg.div(df_agg.sum(axis=0), axis=1) * 100
    df_rel.index.name = rank_name

    df_long = df_rel.reset_index().melt(
        id_vars=rank_name,
        var_name='Sample',
        value_name='Relative Abundance (%)'
    )
    df_long = df_long.rename(columns={rank_name: 'Taxonomy'})
    df_long['Rank'] = rank_name
    return df_long


def generate_otu_data_json(df_otu):
    print("Generating taxonomic data (Family, Genus, Species)...")

    if 'Taxonomy' not in df_otu.columns:
        print("WARNING: 'Taxonomy' column not found. Skipping OTU graphs.", file=sys.stderr)
        return "null", None

    sample_cols = [col for col in df_otu.columns if col != 'Taxonomy']

    # Ensure sample columns are numeric (DuckDB/XLSX can leave object dtype)
    df_otu[sample_cols] = df_otu[sample_cols].apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)

    # OPT-9: Single-pass taxonomy extraction for all ranks
    ranks = _extract_ranks_vectorized(df_otu, sample_cols)

    df_family = aggregate_by_rank(df_otu, sample_cols, ranks['Family'], 'Family', top_n=20)
    df_genus = aggregate_by_rank(df_otu, sample_cols, ranks['Genus'], 'Genus', top_n=15)
    df_species = aggregate_by_rank(df_otu, sample_cols, ranks['Species'], 'Species', top_n=15)

    df_all_ranks = pd.concat([df_family, df_genus, df_species], ignore_index=True)

    composition_json_data = df_all_ranks.to_json(orient='records')

    print("Generating Heatmap graph...")
    df_counts_only = df_otu[sample_cols]
    top_25_otus = df_counts_only.sum(axis=1).nlargest(25).index
    df_top25 = df_counts_only.loc[top_25_otus]
    df_top25_log = np.log1p(df_top25)
    fig_heatmap = px.imshow(
        df_top25_log, title="Top 25 OTU Heatmap (Log-normalized Abundance)",
        labels=dict(x="Sample", y="OTU ID", color="Log(Count+1)"),
        x=df_top25_log.columns, y=df_top25_log.index,
        aspect="auto", height=700
    )
    fig_heatmap_div = pio.to_html(fig_heatmap, full_html=False, include_plotlyjs=False)

    return composition_json_data, fig_heatmap_div


def main():
    options = parse_arguments()

    filter_report_path = Path(options.filter_report)
    otu_table_path = Path(options.otu_table)
    output_html_path = Path(options.output_html)
    template_file = Path(__file__).parent / "template.html"

    if not template_file.exists():
        print("ERROR: 'template.html' file not found.", file=sys.stderr)
        sys.exit(1)

    # OPT-7: Try TSV first (new format), fallback to XLSX (old format)
    if not filter_report_path.exists():
        # Check if the TSV version exists (pipeline now writes .tsv)
        tsv_path = filter_report_path.with_suffix('.tsv')
        xlsx_path = filter_report_path.with_suffix('.xlsx')
        if tsv_path.exists():
            filter_report_path = tsv_path
        elif xlsx_path.exists():
            filter_report_path = xlsx_path

    df_filter, df_otu = load_data(filter_report_path, otu_table_path)
    kpis = get_kpis(df_filter, df_otu)
    graph_filter_counts_div, graph_filter_lengths_div = generate_filter_graphs(df_filter)

    # OTU / Metagenomic section (skipped when OTU table is empty)
    has_otu_data = not df_otu.empty
    if has_otu_data:
        composition_json_data, graph_otu_heatmap_div = generate_otu_data_json(df_otu)
    else:
        print("WARNING: OTU table is empty — skipping metagenomic graphs.")
        composition_json_data, graph_otu_heatmap_div = "null", None

    # Mapping QC section (optional)
    mapping_data, _ = load_mapping_stats(options.mapping_stats)
    mapping_kpis = get_mapping_kpis(mapping_data) if mapping_data else None
    if mapping_data:
        graph_mapping_div, graph_quality_div = generate_mapping_graphs(mapping_data)
        table_mapping_html = generate_mapping_table_html(mapping_data)
    else:
        graph_mapping_div = graph_quality_div = table_mapping_html = None

    print("Converting tables to HTML...")
    table_filter_html = df_filter.to_html(
        classes="table table-striped table-hover table-sm",
        index=False, border=0
    )

    # OPT-10: Limit OTU HTML table to top 500 rows (full table is in XLSX)
    if has_otu_data:
        total_otu_rows = len(df_otu)
        if total_otu_rows > 500:
            # Sort by total abundance and take top 500
            sample_cols = [c for c in df_otu.columns if c != 'Taxonomy']
            df_otu_sorted = df_otu.copy()
            df_otu_sorted['_total'] = df_otu_sorted[sample_cols].sum(axis=1)
            df_otu_sorted = df_otu_sorted.sort_values('_total', ascending=False)
            df_otu_display = df_otu_sorted.head(500).drop(columns=['_total'])
            table_otu_html = df_otu_display.to_html(
                classes="table table-striped table-hover table-sm",
                index=True, border=0, table_id="otu-table"
            )
            table_otu_html += (
                f'<div class="alert alert-info mt-2">'
                f'<small>Showing top 500 of {total_otu_rows:,} OTUs by abundance. '
                f'Full table available in the XLSX file.</small></div>'
            )
            print(f"OTU table limited to 500/{total_otu_rows} rows for HTML.")
        else:
            table_otu_html = df_otu.to_html(
                classes="table table-striped table-hover table-sm",
                index=True, border=0, table_id="otu-table"
            )
    else:
        table_otu_html = None

    print("Rendering final HTML report...")
    template_loader = jinja2.FileSystemLoader(searchpath=Path(__file__).parent)
    template_env = jinja2.Environment(loader=template_loader)
    template = template_env.get_template(template_file.name)

    context = {
        "project_name": options.project_name,
        "report_date": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "kpis": kpis,
        "graph_filter_counts_div": graph_filter_counts_div,
        "graph_filter_lengths_div": graph_filter_lengths_div,
        "table_filter_html": table_filter_html,
        "composition_json_data": composition_json_data,
        "graph_otu_heatmap_div": graph_otu_heatmap_div,
        "table_otu_html": table_otu_html,
        "mapping_kpis": mapping_kpis,
        "graph_mapping_div": graph_mapping_div,
        "graph_quality_div": graph_quality_div,
        "table_mapping_html": table_mapping_html,
    }

    try:
        html_content = template.render(context)
        with open(output_html_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        print(f"\n--- HTML Report Generated Successfully! ---")
        print(f"Open this file in your browser: {output_html_path.resolve()}")

    except Exception as e:
        print(f"ERROR during template rendering: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
